#pragma once

namespace Engine
{
	enum TEXTURETYPE
	{
		TEXTURETYPE_NONE = 0,
		TEXTURETYPE_DIFFUSE = 1,
		TEXTURETYPE_SPECULAR = 2,
		TEXTURETYPE_AMBIENT = 3,
		TEXTURETYPE_EMISSIVE = 4,
		TEXTURETYPE_HEIGHT = 5,
		TEXTURETYPE_NORMALS = 6,
		TEXTURETYPE_ROM = 7,
		TEXTURETYPE_OPACITY = 8,
		TEXTURETYPE_DISPLACEMENT = 9,
		TEXTURETYPE_LIGHTMAP = 10,
		TEXTURETYPE_REFLECTION = 11,
		TEXTURETYPE_BASE_COLOR = 12,
		TEXTURETYPE_NORMAL_CAMERA = 13,
		TEXTURETYPE_EMISSION_COLOR = 14,
		TEXTURETYPE_METALNESS = 15,
		TEXTURETYPE_DIFFUSE_ROUGHNESS = 16,
		TEXTURETYPE_AMBIENT_OCCLUSION = 17,
		//TEXTURETYPE_UNKNOWN = 18,
		TEXTURETYPE_END
	};

	enum class LayerType
	{
		LAYERTYPE_STATIC = 0,
		LAYERTYPE_PICK = 1,
		LAYERTYPE_PLAYER = 2,
		LAYERTYPE_PLANE = 3,
		LAYERTYPE_TRIGGER = 4,
		LAYERTYPE_PLAYER_TRIGGER = 5,
		LAYERTYPE_NPC = 6,
		LAYERTYPE_PLAYER_SKILL = 7,
		LAYERTYPE_ATTAKABLE = 8,
		LAYERTYPE_ITEM = 9,
		LAYERTYPE_FALL_ITEM_STATE0_END = 10,
		LAYERTYPE_Not_AFFECTED_RENDER = 11,
		LAYERTYPE_PLATINGPLATE = 12,
		LAYERTYPE_MONSTER = 13,
		LAYERTYPE_MONSTER_ATTACK = 14,
		LAYERTYPE_MONSTER_FRUIT = 15,
		LAYERTYPE_TRAMPOLINE = 16,
		LAYERTYPE_BLADE = 17,
		LAYERTYPE_BLENDER = 18,
		LAYERTYPE_RAIL = 19,
		LAYERTYPE_BOUNCER = 20,
		LAYERTYPE_CLIMBINGPLANE = 21,
		LAYERTYPE_CLIMBING = 22,
		LAYERTYPE_GRIDDLE = 23,
		LAYERTYPE_BRAINSTROM =24,
		LAYERTYPE_TREASURE = 25,
		LAYERTYPE_KITCHENPAN = 26,
		LAYERTYPE_KITCHENPANBUTTON = 27,
		LAYERTYPE_CLOUD = 28,
		LAYERTYPE_QUEST  = 29,
		LAYERTYPE_ZIP = 30,
		LAYERTYPE_BOSS_DISH = 31,
		LAYERTYPE_BOSS_FOOD_PROJECTILE = 32,
		LAYERTYPE_2DMAP = 33,
		LAYERTYPE_2D_PLAYER = 34,
		LAYERTYPE_2D_MONSTER = 35,
		LAYERTYPE_2D_KEY = 36,
		LAYERTYPE_CAMERA = 97,
		LAYERTYPE_FALL_CABINET = 98,
		LAYERTYPE_ANIMATED_SHELV = 99,
		LAYERTYPE_END = 39 /*Enum 추가시 End 숫자 늘려주삼 */
	};

	enum class PlayerTriggerType
	{
		PTTYPE_CHECKACTOR =0,
		PTTYPE_CHECKHEAD = 1,
		PTTYPE_CHECKTRIGGER =2,
		PTTYPE_CHECKHAND =3,
		PTTYPE_END
	};

	enum class EnviromentTriggerType
	{
		ETTYPE_PARKOUR = 0,
		ETTYPE_LOBOTO  = 1,
		ETTYPE_CLOSE   = 2,
		ETTYPE_CURLING = 3,
		ETTYPE_TUTOMSG = 4,
		ETTYPE_STATE0_END = 5,
		ETTYPE_STATE0_NPC = 6,
		ETTYPE_MONSTER_CREATE = 7,
		ETTYPE_BLENDERPATH = 8,
		ETTYPE_CLIMBING = 9,
		ETTYPE_COOKING = 10,
		ETTYPE_CLIMBINGEND = 11,
		ETTYPE_SLIDE = 12,
		ETTYPE_DEAD = 13,
		ETTYPE_MOUSECUTSCNE = 14,
		ETTYPE_2DMAP = 15,
		ETTYPE_SKILL_INFO= 16,
		ETTYPE_END
	};

	enum class FruitType
	{
		FRUIT_EGG = 0,
		FRUIT_WATERMELON = 1,
		FRUIT_BEEHIVE = 2,
		FRUIT_BREAD = 3,
		FRUIT_ONION = 4,
		FRUIT_PORK = 5,
		FRUIT_STRAWBERRY = 6,
		FRUIT_END
	};

	enum class CookType
	{
		// 기본상태 2
		COOK_IDLE = 0,
		// 끓인상태 4
		COOK_BOIL = 1,
		// 자른상태 8
		COOK_CUT = 2,
		// 간상태 16 
		COOK_BLEND = 3,
		// 구운상태 32
		COOK_BAKE = 4,
		COOK_END
	};

	enum class MonsterType
	{
		MONSTER_CENSOR = 0,
		MONSTER_REGRET = 1,
		MONSTER_DENTURE = 2,
		MONSTER_TOOTHFAIRY = 3,
		MONSTER_CENSORBURLY = 4,
		MONSTER_BADIDEA = 5,
		MONSTER_JUDGE = 6,
		MONSTER_GOATHOLLIS = 7,
		MONSTER_GOATFORD = 8,
		MONSTER_GOATOTTO =9,
		MONSTER_END
	};
}