#pragma once
namespace Client
{
	////IDLE//////
#define PLAYER_IDLE 0
#define	PLAYER_RANDOM_ONE_IDLE 1
#define	PLAYER_RANDOM_TWO_IDLE 2
#define	PLAYER_RANDOM_THREE_IDLE 3
#define	PLAYER_RANDOM_FOR_IDLE 4
#define	PLAYER_RANDOM_FIVE_IDLE 5

	////RUN///
#define PLAYER_RUN_START 6
#define PLAYER_RUN	7
#define PLAYER_RUN_STOP	8

	////WALK////
#define PLAYER_WALK 83
#define PLAYER_WALK_STOP 84

	////BALL////
#define PLAYER_BALL_START	9
#define PLAYER_BALL_START_FAILED	10
#define PLAYER_BALL_END	11
#define	PLAYER_BALL_IDEL 12
#define	PLAYER_BALL_IDEL_TWO 13
#define PLAYER_BALL_RUN 14
#define PLAYER_BALL_RUN_LEFT 80
#define PLAYER_BALL_RUN_RIGHT 81
#define PLAYER_BALL_RUN_BACK 83
#define PLAYER_BALL_WALK 15
#define PLAYER_BALLJUMP_UP 16
#define PLAYER_BALLJUMP_HOLD 17
#define PLAYER_BALLJUMP_DOWN 18
#define PLAYER_BALLJUMP_LAND 19

	////JUMP////
#define PLAYER_JUMP_LEFT_UP 20
#define PLAYER_JUMP_LEFT_HOLD 21
#define PLAYER_JUMP_LEFT_DOWN 22
#define PLAYER_JUMP_RIGHT_UP 23
#define PLAYER_JUMP_RIGHT_HOLD 24
#define PLAYER_JUMP_RIGHT_DOWN 25

#define PLAYER_JUMP_UP 29
#define PLAYER_JUMP_HOLD 30
#define PLAYER_JUMP_DOWN 31

#define PLAYER_DOUBLE_JUMP 82
#define PLAYER_DOUBLE_JUMP_LEFT 32
#define PLAYER_DOUBLE_JUMP_RIGHT 33

	////FALLING////
#define PLAYER_FALLING 34
#define PLAYER_FALLING_INTRO 35

	////LANDING////
#define PALYER_LANDING 36
#define PALYER_LANDING_POSE 37
#define PALYER_LANDING_POSE_TOIDLE 38
#define PALYER_LANDING_DAMAGE 39
#define PALYER_LANDING_DEATH 40

	////DEATH////
#define PLAYER_DEATH_ONE 41
#define PLAYER_DEATH_TWO 42
#define PLAYER_DEATH_ITEM 43

	////HIT////
#define PLAYER_HIT_BACK 44
#define PLAYER_HIT_KNOCKBACK_LOOP 45
#define PLAYER_HIT_KNOCKBACK_END 46


	////ATTACK////
#define PLAYER_ATTACK_COMBO_ONE 47
#define PLAYER_ATTACK_COMBO_TWO 48
#define PLAYER_ATTACK_COMBO_THREE 49


	////QUICKFIRE////
#define PLAYER_PSIBLAST_QUICK_FIRE 50
#define PLAYER_PSIBLAST_CHARGE_LOOP 51
#define PLAYER_PSIBLAST_CHARGE_FIRE 52
#define PLAYER_PSIBLAST_CHARGE_LEFT 53
#define PLAYER_PSIBLAST_CHARGE_RIGHT 54

	////DOWN_ATTACK////
#define PLAYER_DOWN_ATTACK_START 55
#define PLAYER_DOWN_ATTACK_LOOP 56
#define PLAYER_DOWN_ATTACK_END 105


	////GRAP_ATTACK////
#define PLAYER_GRAP_ATTACK_START 58
#define PLAYER_GRAP_ATTACK_CAST 59
#define PLAYER_GRAP_ATTACK_DRAW 60
#define PLAYER_GRAP_ATTACK_DRAW_STATIC 61
#define PLAYER_GRAP_ATTACK_DRAW_LOOP 62
#define PLAYER_GRAP_ATTACK_DRAW_LOOP_STATIC 63
#define PLAYER_GRAP_ATTACK_DRAW_OUT 64

	////DASH////
#define PLAYER_DASH 65
#define PLAYER_DASH_FAILED 66

	////TUMBLE////
#define PLAYER_TUMBLE_ATTACK_START 67
#define PLAYER_TUMBLE_ATTACK_LOOP 68
#define PLAYER_TUMBLE_ATTACK_END 69

	////FLOATING////
#define PLAYER_FLOATING_START 70
#define PLAYER_FLOATING_LOOP 71
#define PLAYER_FLOATING_POPWARN_LOOP 72
#define PLAYER_FLOATING_POP 73
#define PLAYER_FLOATING_END 74

	////INNODE////
#define PLAYER_INNODE_START 75
#define PLAYER_INNODE_LOOP 76
#define PLAYER_INNODE_ARRIVE 77
#define PLAYER_INNODE_DROP 78
#define PLAYER_INNODE_IDLE 79

	////MISC////
	//#define PLAYER_LODING_SCREEN_MOTION 82


	////BRAIN_FIRE////
#define PLAYER_BRAIN_FIRE_LOOP 104
#define PLAYER_BRAIN_FIRE_CASTING 103


	////SLIDER////
#define PLAYER_SLIDER_LEFT 87
#define PLAYER_SLIDER_RIGHT 86

#define PLAYER_DODGE_LEFT 89
#define PLAYER_DODGE_RIGHT 88

#define PLAYER_DODGE_LOOP_LEFT 91
#define PLAYER_DODGE_LOOP_RIGHT 90

#define PLAYER_SLIDER_LOOP_LEFT 93
#define PLAYER_SLIDER_LOOP_RIGHT 92


	////LEDGE_GRAB////

#define PLAYER_UP_LEDGEGRAB 94
#define PLAYER_DOWN_LEDGEGRAB 95
#define PLAYER_LEDGEGRAB_LOOP 96

#define PLAYER_LEDGEGRAB_DOWN 99
#define PLAYER_LEDGEGRAB_LEFT_MOVE 100
#define PLAYER_LEDGEGRAB_RIGHT_MOVE 101

#define PLAYER_LEDGE_GRAB_JUMP 102

	////RAIL_SLIDE////
#define PLAYER_RAIL_SLIDE_ENTER 119
#define PLAYER_RAIL_SLIDE 121
#define PLAYER_RAIL_SLIDE_BACK 122


	////GROUND_SLIDE////
#define PLAYER_GROUND_SLIDE 114


	////Pull_SWITCH////
#define	PLAYER_PULL_SWITCH_ENTER 127
#define	PLAYER_PULL_SWITCH_IDLE	128
#define	PLAYER_PULL_SWITCH_BACKWARD 129
#define PLAYER_PULL_SWITCH_FORWARD 130


	////Trampolione////
#define PLAYER_TRAMPOLINE_ENTER 131

	////Trampolione_HIGH////
#define PLAYER_TRAMPOLINE_HIGH_LOOP 132
#define PLAYER_TRAMPOLINE_HIGH_JUMP 133
#define PLAYER_TRAMPOLINE_HIGH_FALL_FRIST 134
#define PLAYER_TRAMPOLINE_HIGH_FALL_NEXT 135
//이후 랜딩

	////Trampolione_LOW////
#define PLAYER_TRAMPOLINE_LOW_LOOP 136
#define PLAYER_TRAMPOLINE_LOW_FALL_FRIST 137
#define PLAYER_TRAMPOLINE_LOW_FALL_NEXT 138
//이후 랜딩 아면 다시 엔터 랜딩이아니라면 FALL

	////BOUNCER////
#define PLAYER_BOUNCER_JUMP 139
#define PLAYER_BOUNCER_ROLL 140


	////CLIMB////
#define PLAYER_CLIMB_ENTER 141
#define PLAYER_CLIMB_IDLE 142
#define PLAYER_CLIMB_UP 143
#define PLAYER_CLIMB_DOWN 144
#define PLAYER_CLIMB_LEFT 145
#define PLAYER_CLIMB_RIGHT 146
#define PLAYER_CLIMB_JUMP 147
#define PLAYER_CLIMB_UP_LEFT 148
#define PLAYER_CLIMB_UP_RIGHT 149

	////NUCKBACK////
//#define PLAYER_NUCKBACK 163

	////리스폰////
#define PLAYER_RESPAWN 163
	////애니메이션추가시 리스폰 값올려줘야함////
}

using namespace Client;